# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      wget https://github.com/exercism/cli/releases/download/v3.0.13/exercism-linux-64bit.tgz
      tar -zxvf exercism-linux-64bit.tgz
      mv exercism ~/.local/bin/


